### ISSUE TITLE
Incorrectly querying rolls on all connected clients

### ISSUE THREAD

**Issue by guldelox** [spaceman023/Inline-Table-Rolls#12]
This becomes apparent when connected players are using DF Manual Rolls.  I have a bunch of nested roll tables built up for generating random NPCs, but have found that when I trigger these nested tables, players using Manual Rolls get spammed with upwards of 30 roll requests, all on top of one another. Only way to get rid of them quickly is to reload.

**Comment by spaceman023** [comment]
Could you test this issue in the latest release? I don't use that particular module so I wouldn't be able to reproduce the bug.

**Comment by mhoerter** [comment]
I haven't updated to v10 yet (still a couple heavy-use modules that haven't updated yet!) but once I do, I will check to see if this issue is resolved! Thanks for all the hard work!
