### ISSUE TITLE
Plase make it compatible to v.10 of Foundry

### ISSUE THREAD

**Issue by danil0man** [spaceman023/Inline-Table-Rolls#13]
Hello

I use this module very much but is not working with version 10 of Foundry. Can you please make it compatible with v.10?

**Comment by justinthejaguar** [comment]
I can confirm V10 breaks this module in its current state. Is there any chance of an update?

**Comment by danil0man** [comment]
someone made this change which will fix the problem temporarily.
if you open the inline-tables.js in line 11 you can change that line to be this instead
`if (theMessage.user.id === game.user.id) {`

**Comment by danil0man** [comment]
credit to Zhell from The League of Extraordinary Foundry VTT Developers
