### ISSUE TITLE
Inline Table  Rolls not working 

### ISSUE THREAD

**Issue by danil0man** [spaceman023/Inline-Table-Rolls#15]
Hello SpacemanDev. I just updated Inline Table rolls but is not working
![image](https://user-images.githubusercontent.com/72052103/192386242-d3f48051-14e6-4294-a4ba-4299636faf71.png)
I get this error everytime I try to run it

**Comment by spaceman023** [comment]
Hmm that shouldn't be happening. What version of Foundry are you on?

**Comment by danil0man** [comment]
![image](https://user-images.githubusercontent.com/72052103/192555234-46cf14b8-77eb-493a-abe9-2d59027cff07.png)

**Comment by spaceman023** [comment]
I’ll install that system and try to replicate the bug and get back with ya

**Comment by Rox4me1** [comment]
Wanted to add that it doesn't work for me on DCC either :(
![image](https://user-images.githubusercontent.com/114790106/193383466-5bce0262-651f-4b59-b75e-72ab06c03224.png)
