### ISSUE TITLE
Inline rolltable results

### ISSUE THREAD

**Issue by TogaParty** [spaceman023/Inline-Table-Rolls#18]
It would be great if this worked in a text rolltable entry to return multiple results from another table.

I'm working on a lifepath generator for Cyberpunk RED, and at a few steps it calls for 1d10-7 friends, 1d10-7 enemies, and 1d10-7 tragic love affairs.

**Comment by Ulvtand** [comment]
I have succeeded in doing just this:
I have put a line between each table and the table name in bold to make it easier to read.
![image](https://user-images.githubusercontent.com/82996726/204522852-1a43c23b-6651-411d-9994-430e67800ffa.png)
