### ISSUE TITLE
Compendium results

### ISSUE THREAD

**Issue by MaineKnight** [spaceman023/Inline-Table-Rolls#22]
When I have a table call another table multiple times and the called table has compendium results in it the chat display shows them all bunched together. The chat message above is from a table where I inserted html breaks.

![InlineRoll](https://user-images.githubusercontent.com/125476146/219056229-aab0b533-55ac-458b-a999-b81e4dddf22b.JPG)

**Comment by spaceman023** [comment]
Unfortunately cannot fix core foundry formatting.
