### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by rafacrudi** [spaceman023/Inline-Table-Rolls#24]
Seeing a few warnings, not sure what else needs to change.

The module "Inline-Table-Rolls" is using "name" which is deprecated in favor of "id"
The module "Inline-Table-Rolls" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by corerupt83** [comment]
Please Please Please update this module to FvTT  v11. Spent so much time making nested roll tables using this amazing tool. I would be forever grateful if you found the time to do it.  Thanks!
