### ISSUE TITLE
All Inline-Table-Rolls results are null.

### ISSUE THREAD

**Issue by Mozmonar** [spaceman023/Inline-Table-Rolls#25]
As of the latest Foundry update (V11 Stable Build 308) Inline Table Rolls has stopped working and only returns null for the result.
![InlineTableRollsnull](https://github.com/spaceman023/Inline-Table-Rolls/assets/20689320/c34cfef0-ec25-4aaa-b4ae-04cfe43685c9)

**Comment by justinthejaguar** [comment]
Came to report the same.
