### ISSUE TITLE
8/31 Update

### ISSUE THREAD

**Issue by ThreeofSwords** [spaceman023/Inline-Table-Rolls#27]
I was so excited when I saw that an update was supposed to have fixed this module!  (at least that's how I interpreted the 8/31 update).  

This is one of my favorite modules.  I use it often, mostly to create quick random NPCs from dozen of tables.  Canging my syntax as direted now outputs exactly what the input is: ^^#tableName^^ rather than using the table to replace the text.  Maybe it's just me.

**Comment by RomainValy** [comment]
hi! This module is one of my favorite. i tried the new syntax but it doesen't work. ^^#my rolle table^^.

**Comment by ThreeofSwords** [comment]
> hi! This module is one of my favorite. i tried the new syntax but it doesen't work. ^^#my rolle table^^.

I don't see a difference in our examples except the table name.  In your example, your table is called "my rolle table", mine is called "tableName".  Is there a difference I'm missing?  Serious question.  I'd love to be shown my problem.

**Comment by spaceman023** [comment]
Hi, can you both let me know your Foundry version, system version, exact table name, what type of entities the table consists of, and whether you have any errors in the Javascript console related to inline-table-rolls?

**Comment by ThreeofSwords** [comment]
> Hi, can you both let me know your Foundry version, system version, exact table name, what type of entities the table consists of, and whether you have any errors in the Javascript console related to inline-table-rolls?

I just noticed a newer version of this module was available and updated; it seems to work fine now.  Do you still want the requested info?

Note:  I do use Forge for hosting, so my issue could have been related to that.

**Comment by spaceman023** [comment]
That’s ok, thanks, I think it was the issue with the module.json that was messing with Forge installs. Glad it’s fixed for you!

**Comment by RomainValy** [comment]
it works! thank you!

**Comment by ThreeofSwords** [comment]
> That’s ok, thanks, I think it was the issue with the module.json that was messing with Forge installs. Glad it’s fixed for you!

Thank you so much for fixing this module!  I think.  I forgot how many tables I used.  Nested tables within nested tables.  Going through and updating them all makes me wonder if it's worth it.  :)
