### ISSUE TITLE
Request: Allow multiple tablerolls in one command

### ISSUE THREAD

**Issue by FuzzicalLogic** [spaceman023/Inline-Table-Rolls#6]
Pretty much as the title says, I'd like to be able to allow for multiple tablerolls in a single chat command. In particular, it would be nice if it supported dice. A possible example would be:

``[[x#TableName]]`` where ``x`` is the number of times you'd like to roll. If ``x`` could be further replaced by a die roll, that would be even better. (i.e. ``[[[[2d6]]#TableName]]``) The core reason for this is that many loot tables (and some others) within D&D5e utilize a random number of rolls on other tables. This would provide support for that expected functionality that has to be hacked around or compromised.

**Comment by spaceman023** [comment]
It only took me 10 months but this feature has been added in the latest release!
